/*
    Michael Robertson
    IST 271 - Fall 2018
    Chapter 10 Program 5
    The purpose of this program is to allow the user to input the grades of a student for 4 classroom activities and
    then displays the grade report once all the grades are entered.
 */

package com.robertson.app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    // All this code was auto generated by JavaFX
    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("FxLayouts/grades.fxml"));
        primaryStage.setTitle("Grade Entry");
        primaryStage.setScene(new Scene(root, 400, 240));
        primaryStage.show();
    }


    public static void main(String[] args) {
        launch(args);
    }
}
